name: Run tests

on:
  pull_request:
  push:
    paths-ignore:
    - 'COPYRIGHT'
    - 'LICENSE-*'
    - 'README.md'

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: cargo build
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
        version: [1.32.0, stable, nightly]
    runs-on: ${{ matrix.platform }}
    needs: [build]
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: rustup default ${{ matrix.version }}
    - run: cargo build
    - run: cargo test
